# Use Node LTS
FROM node:20-alpine

# Create app directory
WORKDIR /app

# Install dependencies first (better caching)
COPY package*.json ./

RUN npm install

# Copy source code
COPY . .

# Expose Nest default port
EXPOSE 3000

# Start NestJS in development mode (watch)
CMD ["npm", "run", "start:dev"]
